### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by balook** [mzfr/slicer#6]
endpoints , urls must also be extracted

**Comment by mzfr** [comment]
Hey,

I am not going to add this because of multiple reasons:
1) That moves towards the dynamic analysis of the hunting.
2) There are tools for this like [diggit](https://github.com/s0md3v/Diggy)
3) This can also be done via some command like: `grep -ProI "[\"'\`](https?://|/)[\w\.-/]+[\"'\`]" > URL.txt` followed by `sed -i '/schemas\.android\.com/d' URL.txt `
